In [74]:
import pandas as pd
import numpy as np
from statsmodels.stats.inter_rater import fleiss_kappa
from scipy.stats import norm
from sklearn.metrics import cohen_kappa_score

# Preparation

In [75]:
new1 = pd.read_csv('new1.csv')
new2 = pd.read_csv('new2.csv')
old1 = pd.read_csv('old1.csv')
old2 = pd.read_csv('old2.csv')

In [76]:
new1.drop(columns=['комментарий'], inplace=True, errors='ignore')
new1['tag'] = new1['tag'].str.lower()
new1

,example,quote,change,tag
0,В последним предложении он пишет про нас можно...,состовляем,составляем,ortho
1,Я сразу выхожу из комнати и откриваю холодильн...,комнати,комнаты,ortho
2,NaN,откриваю,открываю,ortho
3,NaN,ведеть,видеть,ortho
4,И она дала отпор смерте.,смерте,смерти,ortho
5,В начале двадцатого века в Америке продажа ако...,алкогола,алкоголя,infl
6,"В 1963 он был аресторан, и в следущом году был...",аресторан,арестован,ortho
7,NaN,следущом,следующем,ortho
8,"Парни боятся, что их выганют из школы, но всё ...",выганют,выгонят,ortho
9,Первие признаки осеньи видны на деревьях золот...,осеньи,осени,infl
10,"Он хороший пример "" лишного человека"" русской ...",лишного,лишнего,infl
11,"В Швеции, фирма Ерикссон требует новых рабочых...",рабочых,рабочих,ortho
12,NaN,дале,далее,ortho
13,"Во всяком случае я очень довольна обучениям, к...",обучениям,обучением,ortho
14,"Давним давно семья мыши, которые жили счастлив...",давним,давным,ortho
15,NaN,страна,стране,gov
16,Ну рабочие место я получила.,рабочие,рабочее,ortho
17,В прошлом летом я отдыхала с молодом человеком...,прошлом,прошлым,gov
18,NaN,молодом,молодым,gov
19,До школи я била в детском саду.,школи,школы,ortho
20,NaN,била,была,ortho
21,"Это было для меня важным занятиям, и я ходила ...",занятиям,занятием,ortho
22,Я хорошо училась и была замечательни студент.,замечательни,замечательным,infl gov
23,NaN,студент,студентом,gov
24,"Чем больше Вы будите улыбаться, тем больше Вы ...",будите,будете,ortho
25,"Язык не мертвой, он живой, и постоянно изменяю...",мертвой,мертвый,ortho
26,Последная важная информация о мне – моя фамилия.,последная,последняя,infl
27,Этам летом я буду работаю.,этам,этим,infl
28,"Сдраствуйте, на этой недели не получится прийт...",сдравствуйте,здравствуйте,ortho
29,NaN,недели,неделе,ortho
30,NaN,следущей,следующей,ortho
31,С моим друг играим футбол.,друг,другом,gov
32,NaN,играим,играем,ortho
33,Однако менталитеты оставлся очень традиционнам...,оставлся,оставался,ortho
34,NaN,традиционнами,традиционными,ortho
35,NaN,часа,часов,gov
36,NaN,недело,неделю,infl
37,В США тинейджеры могут работать с шестнадцати ...,высокооплачиваимаю,высокоплачиваемою,ortho
38,Я в них ен разбираюсь и не знаю какой телефон ...,ен,не,ortho
39,NaN,лучшеми,лучшими,ortho
40,NaN,особенностьями,особенностями,infl
41,Один из моих любимих писателей- бразильский пи...,любимих,любимых,ortho
42,"В последнии дни мама пыталась пугать меня, спр...",последнии,последние,ortho
43,"Больше всего от таких условиев страдают дети, ...",условиев,условий,infl
44,Первый раз мы провели время вместе было_ когда...,домашной,домашней,infl
45,В самом новом дополнение Natural Disaster буду...,дополнение,дополнении,gov
46,На данный момент я скучаю по фигурному катанию...,фигуристом,фигуристам,gov
47,В обеeх городах я работал в садике с детми.,обеех,обеих,ortho
48,NaN,детми,детьми,ortho
49,После обеда он немного читал газету и потом он...,маму,маме,gov
50,"Уже давно назад тому, когда я вспоминала своеи...",своеи,свои,ortho
51,NaN,ранные,ранние,ortho
52,Парки там более зелёние и хорошие чем в Стонкг...,зелёние,зелёные,ortho
53,NaN,Стонкгольм,Стокгольме,ortho gov
54,"В настоящим мире на улице кто-то идёт один, кт...",настоящим,настоящем,ortho
55,Все люди ходят в хорошом настроений.,хорошом,хорошем,ortho
56,NaN,настроений,настроении,ortho
57,Мой любимой вид спорта- настольный теннис.,любимой,любимый,ortho
58,"Многое, что мы знаем, передалось нам от древне...",древнех,древних,ortho
59,Надо только сравнивать жизни финнов с жизнью а...,африканцов,африканцев,ortho

In [77]:
new2.drop(columns=['Unnamed: 4'], inplace=True, errors='ignore')
new2['tag'] = new2['tag'].str.lower()
new2

,example,quote,change,tag
0,В последним предложении он пишет про нас можно...,последним,последнем,ortho
1,В последним предложении он пишет про нас можно...,состовляем,составляем,ortho
2,Я сразу выхожу из комнати и откриваю холодильн...,комнати,комнаты,ortho
3,Я сразу выхожу из комнати и откриваю холодильн...,откриваю,открываю,ortho
4,И она дала отпор смерте.,смерте,смерти,infl
5,В начале двадцатого века в Америке продажа ако...,акогола,алкоголя,ortho
6,"В 1963 он был аресторан, и в следущом году был...",аресторан,арестован,ortho
7,"В 1963 он был аресторан, и в следущом году был...",следущом,следующем,infl
8,"Парни боятся, что их выганют из школы, но всё ...",выганют,выгонят,ortho
9,Первие признаки осеньи видны на деревьях золот...,первие,первые,ortho
10,Первие признаки осеньи видны на деревьях золот...,осеньи,осени,ortho
11,Первие признаки осеньи видны на деревьях золот...,золотистами,золотистыми,infl
12,"Он хороший пример "" лишного человека"" русской ...",лишного,лишнего,infl
13,"В Швеции, фирма Ерикссон требует новых рабочых...",рабочых,рабочих,ortho
14,"Во всяком случае я очень довольна обучениям, к...",обучениям,обучением,gov
15,"Давним давно семья мыши, которые жили счастлив...",давним,давным,ortho
16,Ну рабочие место я получила.,рабочие,рабочее,ortho
17,В прошлом летом я отдыхала с молодом человеком...,прошлом,прошлым,gov
18,В прошлом летом я отдыхала с молодом человеком...,молодом,молодым,infl
19,До школи я била в детском саду.,школи,школы,ortho
20,До школи я била в детском саду.,била,была,ortho
21,"Это было для меня важным занятиям, и я ходила ...",занятиям,занятием,gov
22,Я хорошо училась и была замечательни студент.,замечательни,замечательным,infl
23,"Чем больше Вы будите улыбаться, тем больше Вы ...",будите,будете,ortho
24,"Язык не мертвой, он живой, и постоянно изменяю...",мертвой,мертвый,ortho
25,Последная важная информация о мне – моя фамилия.,последная,последняя,infl
26,Этам летом я буду работаю.,этам,этим,infl
27,"Сдраствуйте, на этой недели не получится прийт...",сдраствуйте,здравствуйте,ortho
28,"Сдраствуйте, на этой недели не получится прийт...",недели,неделе,ortho
29,"Сдраствуйте, на этой недели не получится прийт...",следущей,следующей,ortho
30,С моим друг играим футбол.,играим,играем,ortho
31,Однако менталитеты оставлся очень традиционнам...,традиционнами,традиционными,ortho
32,Однако менталитеты оставлся очень традиционнам...,недело,неделю,infl
33,В США тинейджеры могут работать с шестнадцати ...,высокооплачиваимаю,высокооплачиваемую,ortho
34,Я в них ен разбираюсь и не знаю какой телефон ...,лучшеми,лучшими,ortho
35,Я в них ен разбираюсь и не знаю какой телефон ...,особенностьями,особенностями,ortho
36,Один из моих любимих писателей- бразильский пи...,любимих,любимых,ortho
37,"В последнии дни мама пыталась пугать меня, спр...",последнии,последние,ortho
38,"Больше всего от таких условиев страдают дети, ...",условиев,условий,infl
39,Первый раз мы провели время вместе было_ когда...,домашной,домашней,infl
40,В самом новом дополнение Natural Disaster буду...,дополнение,дополнении,gov
41,На данный момент я скучаю по фигурному катанию...,фигуристом,фигуристам,ortho
42,В обеeх городах я работал в садике с детми.,обеeх,обоих,ortho
43,В обеeх городах я работал в садике с детми.,детми,детьми,ortho
44,После обеда он немного читал газету и потом он...,маму,маме,gov
45,"Уже давно назад тому, когда я вспоминала своеи...",ранные,ранние,infl
46,Парки там более зелёние и хорошие чем в Стонкг...,зелёние,зелёные,ortho
47,"В настоящим мире на улице кто-то идёт один, кт...",настоящим,настоящем,ortho
48,Все люди ходят в хорошом настроений.,хорошом,хорошем,ortho
49,Все люди ходят в хорошом настроений.,настроений,настроении,gov
50,Мой любимой вид спорта- настольный теннис.,любимой,любимый,ortho
51,"Многое, что мы знаем, передалось нам от древне...",древнех,древних,ortho
52,Надо только сравнивать жизни финнов с жизнью а...,африканцов,африканцев,ortho

In [78]:

old1.drop(columns=['комментарий', 'доп. тег ortho'], inplace=True, errors='ignore')
old1["tag"] = old1["tag"].str.lower()
old1

,example,quote,change,tag
0,В последним предложении он пишет про нас можно...,последним,последнем,ortho
1,NaN,состовляем,составляем,ortho
2,Я сразу выхожу из комнати и откриваю холодильн...,комнати,комнаты,infl
3,NaN,откриваю,открываю,ortho
4,NaN,ведеть,видеть,ortho
...,...,...,...,...
56,Все люди ходят в хорошом настроений.,хорошом,хорошем,infl
57,NaN,настроений,настроении,gov
58,Мой любимой вид спорта- настольный теннис.,любимой,любимый,gov
59,"Многое, что мы знаем, передалось нам от древне...",древнех,древних,infl
60,Надо только сравнивать жизни финнов с жизнью а...,африканцов,африканцев,infl

In [79]:
old2.drop(columns=['комментарии', 'доп. тег'], inplace=True)
old2["tag"] = old2["tag"].str.lower()
old2

,example,quote,change,tag
0,В последним предложении он пишет про нас можно...,состовляем,составляем,ortho
1,В последним предложении он пишет про нас можно...,последним,последнем,infl
2,Я сразу выхожу из комнати и откриваю холодильн...,комнати,комнаты,gov
3,Я сразу выхожу из комнати и откриваю холодильн...,откриваю,открываю,ortho
4,Я сразу выхожу из комнати и откриваю холодильн...,ведеть,видеть,ortho
...,...,...,...,...
63,Все люди ходят в хорошом настроений.,хорошом,хорошем,infl
64,Все люди ходят в хорошом настроений.,настроений,настроении,gov
65,Мой любимой вид спорта- настольный теннис.,любимой,любимый,ortho
66,"Многое, что мы знаем, передалось нам от древне...",древнех,древних,ortho
67,Надо только сравнивать жизни финнов с жизнью а...,африканцов,африканцев,infl

# Analysis

## Old

In [80]:
merged_old = pd.merge(old1[['quote', 'tag']], old2[['quote', 'tag']], on="quote", suffixes=("_1", "_2"))
merged_old

              quote  tag_1  tag_2
0         последним  ortho   infl
1        состовляем  ortho  ortho
2           комнати   infl    gov
3          откриваю  ortho  ortho
4            ведеть  ortho  ortho
5            смерте  ortho   infl
6           акогола  ortho  ortho
7           акогола   infl  ortho
8         аресторан  ortho  ortho
9          следущом  ortho  ortho
10          выганют  ortho   infl
11           осеньи   infl   infl
12      золотистами  ortho  ortho
13           первие   infl   infl
14          лишного   infl   infl
15          рабочых  ortho  ortho
16        обучениям  ortho    gov
17           давним  ortho  ortho
18          рабочие  ortho  ortho
19            школи  ortho   infl
20             била  ortho  ortho
21         занятиям    gov    gov
22     замечательни   infl   infl
23           будите  ortho  ortho
24          мертвой  ortho  ortho
25        последная   infl   infl
26             этам   infl   infl
27           недели  ortho  ortho
28         следущей  ortho  ortho
29             друг    gov    gov
30           играим  ortho  ortho
31         оставлся  ortho  ortho
32    традиционнами  ortho  ortho
33           недело   infl   infl
34  болеепрестижную  ortho  ortho
35               ен  ortho  ortho
36   особенностьями   infl  ortho
37          любимих  ortho   infl
38        последнии   infl  ortho
39         условиев   infl   infl
40         домашной   infl   infl
41       дополнение    gov  ortho
42       фигуристом    gov  ortho
43            обеех   infl  ortho
44            детми  ortho  ortho
45             маму    gov    gov
46           ранные   infl   infl
47          зелёние   infl   infl
48        настоящим    gov  ortho
49          хорошом   infl   infl
50       настроений    gov    gov
51          любимой    gov  ortho
52          древнех   infl  ortho
53       африканцов   infl   infl

In [81]:
all_labels = sorted(set(merged_old["tag_1"]) | set(merged_old["tag_2"]))

table_old = []
for _, row in merged_old.iterrows():
    counts = [0] * len(all_labels)
    counts[all_labels.index(row["tag_1"])] += 1
    counts[all_labels.index(row["tag_2"])] += 1
    table_old.append(counts)

table_old = pd.DataFrame(table_old, columns=all_labels)

kappa_old = fleiss_kappa(table_old.values)
print(f"Fleiss' kappa: {kappa_old:.4f}")

Fleiss' kappa: 0.4955

In [82]:
print(f"Cohen's kappa: {cohen_kappa_score(merged_old["tag_1"], merged_old["tag_2"]):.4f}")

Cohen's kappa: 0.4965

## New

In [84]:
merged_new = pd.merge(new1[['quote', 'tag']], new2[['quote', 'tag']], on="quote", suffixes=("_1", "_2"))
merged_new

                 quote     tag_1  tag_2
0           состовляем     ortho  ortho
1              комнати     ortho  ortho
2             откриваю     ortho  ortho
3               смерте     ortho   infl
4            аресторан     ortho  ortho
5             следущом     ortho   infl
6              выганют     ortho  ortho
7              лишного      infl   infl
8              рабочых     ortho  ortho
9            обучениям     ortho    gov
10              давним     ortho  ortho
11             прошлом       gov    gov
12             молодом       gov   infl
13            занятиям     ortho    gov
14        замечательни  infl gov   infl
15              будите     ortho  ortho
16             мертвой     ortho  ortho
17           последная      infl   infl
18                этам      infl   infl
19              недели     ortho  ortho
20            следущей     ortho  ortho
21              играим     ortho  ortho
22       традиционнами     ortho  ortho
23              недело      infl   infl
24  высокооплачиваимаю     ortho  ortho
25      особенностьями      infl  ortho
26           последнии     ortho  ortho
27            условиев      infl   infl
28            домашной      infl   infl
29          дополнение       gov    gov
30          фигуристом       gov  ortho
31               детми     ortho  ortho
32                маму       gov    gov
33              ранные     ortho   infl
34             зелёние     ortho  ortho
35           настоящим     ortho  ortho
36             хорошом     ortho  ortho
37          настроений     ortho    gov
38             любимой     ortho  ortho
39             древнех     ortho  ortho
40          африканцов     ortho  ortho

In [85]:
all_labels = sorted(set(merged_new["tag_1"]) | set(merged_new["tag_2"]))

table_new = []
for _, row in merged_new.iterrows():
    counts = [0] * len(all_labels)
    counts[all_labels.index(row["tag_1"])] += 1
    counts[all_labels.index(row["tag_2"])] += 1
    table_new.append(counts)

table_new = pd.DataFrame(table_new, columns=all_labels)

kappa_new = fleiss_kappa(table_new.values)
print(f"Fleiss' kappa: {kappa_new:.4f}")

Fleiss' kappa: 0.5411

In [86]:
print(f"Cohen's kappa: {cohen_kappa_score(merged_new["tag_1"], merged_new["tag_2"]):.4f}")

Cohen's kappa: 0.5455

## Statistical tests

For Fleiss' kappa

In [88]:
def fleiss_se(table):
    N, k = table.shape
    n = table.sum(axis=1)[0]
    P_bar = table.sum(axis=0) / (N * n)
    P_e = np.sum(P_bar**2)
    kappa = fleiss_kappa(table)
    # оценка дисперсии по Fleiss (1979)
    var = (2 * (N - 1) * (P_e * (1 - P_e))) / (N * n * (n - 1) * (1 - P_e)**2)
    return np.sqrt(var)


se_old = fleiss_se(table_old)
se_new = fleiss_se(table_new)

z = (kappa_new - kappa_old) / np.sqrt(se_old**2 + se_new**2)
p_value = norm.sf(abs(z))

print(f"κ old: {kappa_old:.4f}, SE old: {se_old:.4f}")
print(f"κ new: {kappa_new:.4f}, SE new: {se_new:.4f}")
print(f"z: {z:.4f}, p-value: {p_value:.4f}")

κ old: 0.4955, SE old: 0.8305
κ new: 0.5411, SE new: 0.9273
z: 0.0367, p-value: 0.4854

For Cohen's kappa

In [89]:
def cohen_se(tags1, tags2):
    N = len(tags1)
    po = np.mean(tags1 == tags2)
    labels1 = np.unique(tags1)
    labels2 = np.unique(tags2)
    pe = sum([(np.mean(tags1 == l1) * np.mean(tags2 == l1)) for l1 in labels1])
    kappa = (po - pe) / (1 - pe)
    se = np.sqrt(po * (1 - po) / (N * (1 - pe)**2))
    return kappa, se

kappa_old, se_old = cohen_se(merged_old['tag_1'].values, merged_old['tag_2'].values)
kappa_new, se_new = cohen_se(merged_new['tag_1'].values, merged_new['tag_2'].values)

z = (kappa_new - kappa_old) / np.sqrt(se_old**2 + se_new**2)
p_value = norm.sf(abs(z))

print(f"κ old: {kappa_old:.4f}, SE old: {se_old:.4f}")
print(f"κ new: {kappa_new:.4f}, SE new: {se_new:.4f}")
print(f"z: {z:.4f}, p-value: {p_value:.4f}")

κ old: 0.4965, SE old: 0.1056
κ new: 0.5455, SE new: 0.1250
z: 0.2992, p-value: 0.3824