In [94]:
import pandas as pd
import numpy as np
from statsmodels.stats.inter_rater import fleiss_kappa
from scipy.stats import norm

# Preparation

In [95]:
new1 = pd.read_csv('new1.csv')
new2 = pd.read_csv('new2.csv')
new3 = pd.read_csv('new3.csv')
old1 = pd.read_csv('old1.csv')
old2 = pd.read_csv('old2.csv')
old3 = pd.read_csv('old3.csv')

In [96]:
new1.drop(columns=['комментарий'], inplace=True)
new1["tag"] = new1["tag"].str.lower().str.replace("+", " ", regex=False)
new1

,example,tag,quote,change
0,Когда я поехола в Париж и первый раз пошла на ...,ortho,поехола,поехала
1,NaN,misspell,Эфельную,Эйфелевую
2,NaN,ortho,циганей,цыган
3,"Кочегар – пероидически положит уголь в камин, ...",ortho,пероидически,периодически
4,Туристы смогут осмотреть многоэтажные брощенны...,ortho,брощенные,брошенные
...,...,...,...,...
77,1. Там он встречает одну девушку которая его в...,misspell,вдухвляет,вдохновляет
78,1. Весь год она работала болентором в центре д...,ortho typo,болентором,волонтером
79,1. В первом сценарий главная героиня на карабл...,ortho,карабле,корабле
80,NaN,ortho,сталом,столом
81,NaN,ortho,пишит,пишет

In [97]:
new2.drop(columns=['Обоснование'], inplace=True)
new2["tag"] = new2["tag"].str.lower().str.replace("+", " ", regex=False)
new2

,example,tag,quote,change
0,Когда я поехола в Париж и первый раз пошла на ...,ortho,поехола,поехала
1,NaN,misspell,Эфельную,Эйфелеву
2,NaN,ortho,циганей,цыганей
3,"Кочегар – пероидически положит уголь в камин, ...",ortho,пероидически,периодически
4,Туристы смогут осмотреть многоэтажные брощенны...,typo,брощенные,брошенные
...,...,...,...,...
82,Весь год она работала болентором в центре для ...,misspell,болентором,волонтером
83,В первом сценарий главная героиня на карабле с...,ortho,сценарий,сценарии
84,NaN,ortho,карабле,корабле
85,NaN,ortho,сталом,столом
86,NaN,ortho,пишит,пишет

In [98]:
new3.drop(columns=['обоснование'], inplace=True)
new3["tag"] = new3["tag"].str.lower().str.replace("+", " ", regex=False)
new3

,example,tag,quote,change
0,Когда я поехола в Париж и первый раз пошла на ...,ortho,поехола,поехала
1,NaN,ortho,циганей,цыганей
2,"Кочегар – пероидически положит уголь в камин, ...",ortho,пероидически,периодически
3,Туристы смогут осмотреть многоэтажные брощенны...,typo,брощенные,брошенные
4,В это петлю попадает каждий иммигрант который ...,ortho,это,эту
...,...,...,...,...
82,Весь год она работала болентором в центре для ...,typo,болентором,волонтёром
83,NaN,ortho,NaN,NaN
84,NaN,ortho,NaN,NaN
85,В первом сценарий главная героиня на карабле с...,ortho,карабле,корабле
86,NaN,ortho,сталом,столом

In [99]:

old1.drop(columns=['Комментарии', 'комментарии еще будут дополняться'], inplace=True)
old1['tag'] = old1['tag'].str.lower().str.replace("+", " ", regex=False)
old1

,example,quote,change,tag
0,Когда я поехола в Париж и первый раз пошла на ...,поехола,поехала,ortho
1,Когда я поехола в Париж и первый раз пошла на ...,Эфельную,Эйфелеву,misspell
2,Когда я поехола в Париж и первый раз пошла на ...,циганей,цыган,misspell
3,"Кочегар – пероидически положит уголь в камин, ...",пероидически,периодически,misspell
4,Туристы смогут осмотреть многоэтажные брощенны...,брощенные,заброшенные,ortho
...,...,...,...,...
79,Там он встречает одну девушку которая его вдух...,вдухвляет,вдохновляет,misspell
80,Весь год она работала болентором в центре для ...,болентором,волонтером,misspell
81,В первом сценарий главная героиня на карабле с...,карабле,корабле,ortho
82,В первом сценарий главная героиня на карабле с...,сталом,столом,ortho
83,В первом сценарий главная героиня на карабле с...,пишит,пишет,ortho

In [100]:
old2.drop(columns=['Другой тег', 'Доп. тег'], inplace=True)
old2['tag'] = old2['tag'].str.lower()
old2

,example,quote,change,tag
0,Когда я поехола в Париж и первый раз пошла на ...,поехола,поехала,ortho
1,Когда я поехола в Париж и первый раз пошла на ...,Эфельную,Эйфелеву,misspell
2,Когда я поехола в Париж и первый раз пошла на ...,циганей,цыган,misspell
3,"Кочегар – пероидически положит уголь в камин, ...",пероидически,периодически,misspell
4,Туристы смогут осмотреть многоэтажные брощенны...,брощенные,брошенные,ortho
...,...,...,...,...
57,Нескольких моих друзей купили компутерные очки...,третые,третьи,misspell
58,Там он встречает одну девушку которая его вдух...,вдухвляет,вдохновляет,misspell
59,Весь год она работала болентором в центре для ...,болентором,волонтером,misspell
60,В первом сценарий главная героиня на карабле с...,карабле,корабле,ortho
61,В первом сценарий главная героиня на карабле с...,сталом,столом,ortho

In [101]:
old3.drop(columns=['комментарий'], inplace=True)
old3['tag'] = old3['tag'].str.lower().str.replace("+", " ", regex=False)
old3

,example,quote,change,tag
0,Когда я поехола в Париж и первый раз пошла на ...,поехола,поехала,ortho
1,Когда я поехола в Париж и первый раз пошла на ...,Эфельную,Эйфелеву,misspell
2,Когда я поехола в Париж и первый раз пошла на ...,циганей,цыган,misspell
3,"Кочегар – пероидически положит уголь в камин, ...",пероидически,переодически,misspell
4,Туристы смогут осмотреть многоэтажные брощенны...,брощенные,брошенные,ortho
...,...,...,...,...
74,Там он встречает одну девушку которая его вдух...,вдухвляет,вдохновляет,misspell
75,Весь год она работала болентором в центре для ...,болентором,волонтером,misspell
76,В первом сценарий главная героиня на карабле с...,карабле,корабле,ortho
77,В первом сценарий главная героиня на карабле с...,сталом,столом,ortho
78,В первом сценарий главная героиня на карабле с...,пишит,пишет,ortho

# Analysis

## Old

In [102]:
merged_old = pd.merge(old1[['quote', 'tag']], 
                      old2[['quote', 'tag']], 
                      on="quote", 
                      suffixes=("_1", "_2"))

merged_old = pd.merge(merged_old, 
                      old3[['quote', 'tag']], 
                      on="quote")

merged_old = merged_old.rename(columns={"tag": "tag_3"})
merged_old

           quote     tag_1     tag_2     tag_3
0        поехола     ortho     ortho     ortho
1       Эфельную  misspell  misspell  misspell
2        циганей  misspell  misspell  misspell
3   пероидически  misspell  misspell  misspell
4      брощенные     ortho     ortho     ortho
..           ...       ...       ...       ...
60        третые  misspell  misspell  misspell
61     вдухвляет  misspell  misspell  misspell
62    болентором  misspell  misspell  misspell
63       карабле     ortho     ortho     ortho
64        сталом     ortho     ortho     ortho

[65 rows x 4 columns]

In [103]:
all_labels = sorted(set(merged_old["tag_1"]) | set(merged_old["tag_2"]) | set(merged_old["tag_3"]))

table_old = []
for _, row in merged_old.iterrows():
    counts = [0] * len(all_labels)
    counts[all_labels.index(row["tag_1"])] += 1
    counts[all_labels.index(row["tag_2"])] += 1
    counts[all_labels.index(row["tag_2"])] += 1
    table_old.append(counts)

table_old = pd.DataFrame(table_old, columns=all_labels)

kappa_old = fleiss_kappa(table_old.values)
print("Fleiss' kappa:", kappa_old)

Fleiss' kappa: 0.8784895314057826

## New

In [104]:
merged_new = pd.merge(new1[['quote', 'tag']], 
                      new2[['quote', 'tag']], 
                      on="quote", 
                      suffixes=("_1", "_2"))

merged_new = pd.merge(merged_new, 
                      new3[['quote', 'tag']], 
                      on="quote")

merged_new.columns = ["quote", "tag_1", "tag_2", "tag_3"]

merged_new

           quote       tag_1     tag_2     tag_3
0        поехола       ortho     ortho     ortho
1        циганей       ortho     ortho     ortho
2   пероидически       ortho     ortho     ortho
3      брощенные       ortho      typo      typo
4         каждий       ortho     ortho     ortho
..           ...         ...       ...       ...
74       хорошым       ortho     ortho     ortho
75     вдухвляет    misspell  misspell  misspell
76    болентором  ortho typo  misspell      typo
77       карабле       ortho     ortho     ortho
78        сталом       ortho     ortho     ortho

[79 rows x 4 columns]

In [105]:
all_labels = sorted(set(merged_new["tag_1"]) | set(merged_new["tag_2"]) | set(merged_new["tag_3"]))

table_new = []
for _, row in merged_new.iterrows():
    counts = [0] * len(all_labels)
    counts[all_labels.index(row["tag_1"])] += 1
    counts[all_labels.index(row["tag_2"])] += 1
    counts[all_labels.index(row["tag_3"])] += 1
    table_new.append(counts)

table_new = pd.DataFrame(table_new, columns=all_labels)

kappa_new = fleiss_kappa(table_new.values)
print(f"Fleiss' kappa: {kappa_new:.4f}")

Fleiss' kappa: 0.5737

## Statistical tests

In [107]:
def fleiss_se(table):
    N, k = table.shape
    n = table.sum(axis=1)[0]
    P_bar = table.sum(axis=0) / (N * n)
    P_e = np.sum(P_bar**2)
    kappa = fleiss_kappa(table)
    var = (2 * (N - 1) * (P_e * (1 - P_e))) / (N * n * (n - 1) * (1 - P_e)**2)
    return np.sqrt(var)


se_old = fleiss_se(table_old)
se_new = fleiss_se(table_new)

z = (kappa_new - kappa_old) / np.sqrt(se_old**2 + se_new**2)
p_value = norm.sf(abs(z))

print(f"κ old: {kappa_old:.4f}, SE old: {se_old:.4f}")
print(f"κ new: {kappa_new:.4f}, SE new: {se_new:.4f}")
print(f"z: {z:.4f}, p-value: {p_value:.4f}")

κ old: 0.8785, SE old: 0.6704
κ new: 0.5737, SE new: 0.5353
z: -0.3552, p-value: 0.3612

Resusts are statistically irrelevant because of high standart errors